### ISSUE TITLE
ModuleNotFoundError: No module named 'libnacl

### ISSUE THREAD

**Issue by dbrouwer1979** [jheling/freeathome#47] opened 2020-04-15 19:47 UTC
Since recent update of HA to version 0.108.x I am getting this error:
Logger: homeassistant.setup
Source: custom_components/freeathome/fah/crypto.py:3
First occurred: 21:30:14 (1 occurrences)
Last logged: 21:30:14

Error during setup of component freeathome
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 171, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/freeathome/__init__.py", line 32, in async_setup
    from . import pfreeathome
  File "/config/custom_components/freeathome/pfreeathome.py", line 24, in <module>
    from .fah.saslhandler import SaslHandler
  File "/config/custom_components/freeathome/fah/saslhandler.py", line 7, in <module>
    from .crypto import Crypto, loginSaslPayload, buildSaslResponse
  File "/config/custom_components/freeathome/fah/crypto.py", line 3, in <module>
    import libnacl
ModuleNotFoundError: No module named 'libnacl'

I'm on SysApp 2.5.0

**Comment by jeroen84** [comment] 2020-04-16 08:28
I experienced the same issue on a fresh Docker image. What fixes the issue is to include 'libnacl' as a requirement in the manifest. I will make a pull request.

**Comment by jeroen84** [comment] 2020-04-16 08:30
I noticed there is a pull request already addressing this issue: https://github.com/jheling/freeathome/pull/45 :-)

**Comment by dbrouwer1979** [comment] 2020-04-16 19:28
Thank you Jeroen, that worked!

**Comment by jheling** [comment] 2020-04-19 08:51
The pull request has been merged into the repository

**Closed by jheling** 2020-04-19 08:51 UTC
