### ISSUE TITLE
binary_sensor/turn_on service not found

### ISSUE THREAD

**Issue by Tau-Neutrino** [jheling/freeathome#87] opened 2021-01-10 17:15 UTC
Hi,

I wanted to include my free@home setup into home assistant. 
To start: I am new to homeassistant, so I might just miss a point here!

I followed the instruction and after providing my credentials my free@home devices were available in home assistant.

I do see the status of the devices in home assistant - e.g if I switch on a light with the light swith on the wall, the status changes in home assistant. But it seems like I am not able to control the light within home assistant since i always get the error:
`binary_sensor/turn_on service not found`

Here is my setup:
SysAP 
  Version: 2.5.5
  Revision: 7857

homeassistant runs on an Pi4 with:
2020.12.7 / homeassistant OS 5.10 

BR, TN

**Comment by EnricoBilla** [comment] 2021-01-10 17:28
It seems like you're trying to turn on a `binary_sensor`, which is in fact just a sensor. If you want to turn on the light you should call the `light.turn_on` service on your `light ` entity

**Comment by Tau-Neutrino** [comment] 2021-01-10 17:47
Thanks! For each Busch-jaeger device I get a binary_sensor and a light entity. 
For the light entities i always geht 
`This entiy does not have a unique ID` error. I will try creating a unique ID manually and check again!

**Comment by Tau-Neutrino** [comment] 2021-01-13 18:39
here is an update:

switching the light entities runs flawlessly! However, a lot of the light enties did not get a unique Id assigned to them after the import! to fix this, i had to reload the freeathome integration several times! After each reload, some more light entities got assigned a unique ID for some reason....
![grafik](https://user-images.githubusercontent.com/20402123/104494713-18f57080-55d7-11eb-88a0-ebee3693e268.png)

**Comment by Tho85** [comment] 2021-01-13 20:36
The problem is that the default names in free@home (Ⓐ, ⓑ etc.) are not correctly converted to entity IDs. This is why it says `light.` without an actual name afterwards in your screenshot. There is an open PR (home-assistant/core#43153) in Home Assistant to fix this issue, which has not been merged yet.

So you could either rename all entities through the free@home web UI from names like Ⓐ and ⓑ to something useful, or you could wait until the mentioned PR is merged. It has been approved some days ago, but I don't know when it will be merged.

**Comment by Tho85** [comment] 2021-02-03 22:40
According to the [release notes](https://www.home-assistant.io/blog/2021/02/03/release-20212/), the fix has made it into the latest Home Assistant release (2021.2.0), so you might want to try and upgrade your Home Assistant installation.

**Closed** 2021-07-16 14:37 UTC
